default: &DEFAULT
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["POSTGRESQL_USER"] || ENV["USER"] || 'postgres' %>
  password: <%= ENV["POSTGRESQL_PASSWORD"] %>
  host: <%= ENV["POSTGRESQL_HOST"] || 'localhost' %>
  pool: <%= ENV["POSTGRESQL_POOL"] || 5 %>
  port: <%= ENV["POSTGRESQL_PORT"] || 5432 %>

development:
  <<: *DEFAULT
  database: pipefy_exercise_development

test:
  <<: *DEFAULT
  database: pipefy_exercise_test

production:
  <<: *DEFAULT
  database: pipefy_exercise_production
